// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1652401018);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1652427300);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1652545437);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1652400898);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1652401138);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.download.autohideButton", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{819f5539-739d-4cf6-ab18-45678e795c4e}");
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"canvasblocker_kkapsner_de\"],\"idsInUrlbar\":[\"canvasblocker_kkapsner_de\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "/S92rzfUdA8IqLNkEq93Ow==");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3933192/ublock_origin-1.42.4-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1652545191088");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1652566791088");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.lastColdStartupCheck", 1652545698);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\",\"canvasblocker_kkapsner_de-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"_3579f63b-d8ee-424f-bbb6-6d0ce3285e6a_-browser-action\",\"canvasblocker_kkapsner_de-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("distribution.iniFile.exists.appversion", "100.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "bdf6d521f24143c7bc785469d55da30a");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20220505082543");
user_pref("extensions.lastAppVersion", "100.0");
user_pref("extensions.lastPlatformVersion", "100.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.CanvasBlocker@kkapsner.de", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"258ba887-da4b-4ac9-b623-50b44e7c1fa5\",\"pictureinpicture@mozilla.org\":\"753ffc4b-abb4-4099-a905-26ebf6bb3e87\",\"screenshots@mozilla.org\":\"9d1f342a-e985-4900-a1dc-00e7f4389b27\",\"webcompat@mozilla.org\":\"c2d15468-07e4-4618-9361-d30fe39e2682\",\"default-theme@mozilla.org\":\"24a7a3d3-290e-40fa-93a2-884bcd24229a\",\"addons-search-detection@mozilla.com\":\"71c5ec8f-fac8-4a47-aa2f-cdeedead8fb8\",\"wikipedia@search.mozilla.org\":\"e083aa81-812a-4bf2-837a-e76f8345e962\",\"ddg@search.mozilla.org\":\"77ec5e19-a049-4d43-b195-70e6ca4735ed\",\"uBlock0@raymondhill.net\":\"d3b3eaf6-1235-432a-9f18-978f1d19f90d\",\"CanvasBlocker@kkapsner.de\":\"3cf88a85-9950-4e2d-bfb5-bf04e90abaaa\",\"{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}\":\"7e240047-0a42-4bb7-b8fe-041b49935d82\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1652400633);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20220505082543");
user_pref("media.gmp-manager.lastCheck", 1652400704);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.http.referer.XOriginPolicy", 2);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.enabled", false);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.resistFingerprinting.letterboxing", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.extension", "CanvasBlocker@kkapsner.de");
user_pref("reader.color_scheme", "light");
user_pref("security.sandbox.content.tempDirSuffix", "406df47f-ea70-4782-bd70-121eb66044ea");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1652545696);
user_pref("toolkit.telemetry.cachedClientID", "f60f7b58-e187-4e73-9891-82bbcc715690");
user_pref("webgl.disabled", false);
